### ISSUE TITLE
Checkpoint link is invalid

### ISSUE THREAD

**Issue by YuFan-Microsoft** [dreasysnail/RetGen#1]
Seems the link for checkpoint and data is no longer valid

**Comment by VCDragoon** [comment]
This has been the case for a few weeks now - would love an update! Can't reproduce without even the base data...

**Comment by SeaEagleI** [comment]
> Seems the link for checkpoint and data is no longer valid

Hello YuFan, how did you solve this problem? Have you reproduced the paper successfully yet?

**Comment by dreasysnail** [comment]
Sorry for the delay. Data link is updated. Thanks.
